version: "3.7"
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: enota
    restart: always
    ports:
      - "81:80"
    volumes:
      - .:/var/www/html
    # depends_on:
    #   - db
    # links:
    #   - db

  # db:
  #     # image: mysql:5.7
  #     image: mariadb:10.4
  #     container_name: mysql
  #     command: --default-authentication-plugin=mysql_native_password
  #     working_dir: /var/lib/mysql
  #     restart: always
  #     ports:
  #     - "3306:3306"
  #     environment:
  #       MYSQL_USER: root
  #       MYSQL_PASSWORD: admin
  #       MYSQL_ROOT_PASSWORD: admin
  #       MYSQL_DATABASE: enota
  #     volumes:
  #     - ./mysql:/var/lib/mysql
